### ISSUE TITLE
is this plugin fork by @an-rahulpandey

### ISSUE THREAD

**Issue by bau720123** [grupoiris/phonegap-plug-ios-audio#1]
hi @grupoiris 
is this plugin fork by @an-rahulpandey 
because it look like almost the same
https://www.npmjs.com/package/cordova-plugin-iosaudiopicker
https://github.com/an-rahulpandey/ios-audio-picker

if yes
what the difference between by repo and yours ?

**Comment by grupoiris** [comment]
hello bau, we fork the original project from @an-rahulpandey because he is try to convert the audio file in .m4a format and keep the result in the path of the application; we only need the data to use the original audio file.

**Comment by bau720123** [comment]
got it
thanks @grupoiris
